#!/bin/bash
# Quick Start Guide for Execution Modes
# This file shows the fastest way to run the system in each mode

echo "========================================================================"
echo "Industrial PDF-to-Graph Pipeline - Quick Start"
echo "========================================================================"
echo ""
echo "Two execution modes are available:"
echo ""
echo "1. LOCAL CPU MODE (for testing all features locally)"
echo "   └─ No time restrictions, good for debugging"
echo ""
echo "2. GPU SERVER MODE (for optimized production processing)"
echo "   └─ GPU acceleration, configurable timeouts"
echo ""
echo "========================================================================"
echo ""
echo "QUICK START COMMANDS:"
echo ""
echo "--- Local Testing (CPU) ---"
echo "# Just run this:"
echo "$ ./run_all.sh"
echo ""
echo "# Or explicitly set CPU mode:"
echo "$ export EXECUTION_MODE=cpu"
echo "$ ./run_all.sh"
echo ""
echo "--- Production (GPU) ---"
echo "# Set GPU mode:"
echo "$ export EXECUTION_MODE=gpu"
echo "$ ./run_all.sh"
echo ""
echo "--- Production with Timeouts ---"
echo "$ export EXECUTION_MODE=gpu"
echo "$ export TABLE_EXTRACTION_TIMEOUT=180  # 3 minutes max"
echo "$ export OCR_PROCESSING_TIMEOUT=300    # 5 minutes max"
echo "$ ./run_all.sh"
echo ""
echo "========================================================================"
echo ""
echo "AVAILABLE ENVIRONMENT VARIABLES:"
echo ""
echo "EXECUTION_MODE"
echo "  Values: cpu (default), gpu"
echo "  Controls device placement and optimization"
echo ""
echo "TABLE_EXTRACTION_TIMEOUT"
echo "  Values: 0 (no limit, default), or seconds"
echo "  Max time for table extraction"
echo ""
echo "OCR_PROCESSING_TIMEOUT"
echo "  Values: 0 (no limit, default), or seconds"
echo "  Max time for OCR processing"
echo ""
echo "PDF_RENDER_TIMEOUT"
echo "  Values: 0 (no limit, default), or seconds"
echo "  Max time for PDF rendering"
echo ""
echo "========================================================================"
echo ""
echo "CHECKING YOUR SETUP:"
echo ""
echo "Check GPU availability:"
echo "$ nvidia-smi"
echo ""
echo "Check current mode in logs:"
echo "$ grep '\[CONFIG\] Execution Mode' logs/run_all.log"
echo ""
echo "========================================================================"
echo ""
echo "For detailed information, see:"
echo "  - EXECUTION_MODES.md (comprehensive guide)"
echo "  - FIXES_SUMMARY.md (what was changed)"
echo ""
echo "========================================================================"
